package com.app.solaro.activity

import android.os.Bundle
import android.widget.Button
import android.widget.EditText
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.app.solaro.database.DatabaseHelper
import com.app.solaro.utils.PasswordHasher
import com.solaro.app.R
import com.solaro.models.User

class RegisterActivity : AppCompatActivity() {

    private lateinit var dbHelper: DatabaseHelper

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContentView(R.layout.activity_register)

        dbHelper = DatabaseHelper(this)

        val etRegUsername = findViewById<EditText>(R.id.etRegUsername)
        val etRegEmail = findViewById<EditText>(R.id.etRegEmail)
        val etRegPassword = findViewById<EditText>(R.id.etRegPassword)
        val etRegConfirmPassword = findViewById<EditText>(R.id.etRegConfirmPassword)
        val btnRegister = findViewById<Button>(R.id.btnRegister)

        btnRegister.setOnClickListener {
            val username = etRegUsername.text.toString().trim()
            val email = etRegEmail.text.toString().trim()
            val password = etRegPassword.text.toString().trim()
            val confirmPassword = etRegConfirmPassword.text.toString().trim()

            if (username.isEmpty() || email.isEmpty() || password.isEmpty()) {
                Toast.makeText(this, "Please fill all fields", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            if (password != confirmPassword) {
                Toast.makeText(this, "Passwords do not match", Toast.LENGTH_SHORT).show()
                etRegPassword.error = "Passwords do not match"
                etRegConfirmPassword.error = "Passwords do not match"
                return@setOnClickListener
            }

            // IMPROVEMENT: Check if username OR email already exist.
            if (dbHelper.getUserByUsername(username) != null) {
                Toast.makeText(this, "Username already exists", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }
            if (dbHelper.getUserByEmail(email) != null) { // Assumes you add this function to DatabaseHelper
                Toast.makeText(this, "Email is already registered", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            val hashedPassword = PasswordHasher.hashPassword(password)

            // Note: This assumes your User model and addUser function are set up correctly.
            val newUser = User(
                id = 0, // ID will be auto-generated by the database
                username = username,
                email = email,
                passwordHash = hashedPassword,
                userType = "user" // Default to regular user
            )

            val result = dbHelper.addUser(newUser)
            if (result != -1L) {
                Toast.makeText(this, "Registration Successful! Please login.", Toast.LENGTH_LONG).show()
                finish() // Go back to LoginActivity
            } else {
                Toast.makeText(this, "Registration failed. Try again.", Toast.LENGTH_SHORT).show()
            }
        }
    }
}